# Source: circleci-simple-app/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: circleci-simple-app
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port:   "3000"
      labels:
        app: circleci-simple-app
    spec:
      containers:
      - name: circleci-simple-app
        image: gcr.io/storied-parser-268912/circleci-simple-app:CIRCLE_BRANCH
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
