---
# Source: circleci-simple-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: circleci-simple-app
  annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port:   "3000"
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: circleci-simple-service
  selector:
    app: circleci-simple-app
