version: 2.1

orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.0.3
  gcr: circleci/gcp-gcr@0.6.1
  Kubernetes: circleci/kubernetes@0.11.0

jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: circleci-simple-app
          tag: $CIRCLE_BRANCH
      - gcr/push-image:
          image: circleci-simple-app
          tag: $CIRCLE_BRANCH

    
  test-deploy:
    description: Deploy application to Google Kubernetes Engine on user namespace
    machine: true
    steps:
      - checkout
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: dsq-hpe-cluster-1
          perform-login: true
          install-kubectl: true
      - run:
          name: Deploy using kustomize
          command: |
            kubectl apply -k deploy-kustomize -n $CIRCLE_USERNAME
  prod-deploy:
    description: Deploy application to Google Kubernetes Engine on production branch
    machine: true
    steps:
      - checkout
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: dsq-hpe-cluster-1
          perform-login: true
          install-kubectl: true
      - run:
          name: Deploy using kustomize
          command: |
            kubectl apply -k deploy-kustomize -n default

workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
          context: gke
          requires:
            - build
      - test-deploy:
          context: gke
          requires:
            - Build-Push-Image-Docker
          filters:
            branches:
              ignore:
                - master

      - prod-deploy:
          context: gke
          requires:
            - Build-Push-Image-Docker
          filters:
            branches:
               only: master

