jobs:
  build:
    machine: true
    steps:
      - checkout
      - kube-orb/install-kubeconfig:
          kubeconfig: 'YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VONVJF
TkRRV0pEWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBW
UldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkpkMDFFU1hsUFJFVTFUV3BK
ZUU5V2IxaEVWRTEzVFVSSmVVNVVSVFZOYWtsNFQxWnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZ
VE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJW
QkJSRU5EUVZGdlEyZG5SVUpCVHpST0NuRldVaXR3WjBacU1VTldNVEIyVWxoeGRXWnVSV1JEVUZS
c0szTnFTM0ozUjNCMlRtVnNhV1kyVlhGdFRteFBUVFZWTnpFck5EaE5hbWxyYWtabk9Vc0tVU3Rt
ZVROeVdHZFVTSEF4VkRWS1VrNVViSEJFYVM5ck0xUnNTVTFuUTBGWE5uY3pjaXROWWtaRVQzTldi
bFV6TjFGdFNrcG5jbE12YzI5emFpdEVXQXAxY2pGV1NuazNTVTkxZDBNNVZGa3pVVk00Tmt3MFZF
eDVTR2hOTkhGSk4zVTNjbVZKYWtaeU9FSk9iVFU0UVV0SE4yeGFWMmQzV2xCRmMwczBMM3BSQ2pj
eVNuUldRVmRtTjNJclpraERVVEZaYkVGV2JVcHBWazFhWWpSd2JqQTBjWFUxT1Zrd2JITm5OR05U
VVRCSWJrcEJVR3BLZUdWbU1rRmhVVEp5V2trS0sxaENTbkpQYzA1SlZYTktla1pvYUhaVU1VMUNV
V1JhTVRaUVEyZFNRbmxtV25oWVozQjJURGRrWVhabVoyaGtWWFF4Y0hkMmRUTjNRakJqWTBnM2J3
cFRNWEprYTJOSlFrSTJMekJaVW5SNFRVOVZRMEYzUlVGQllVMXFUVU5GZDBSbldVUldVakJRUVZG
SUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBSUldVcExiMXBK
YUhaalRrRlJSVXhDVVVGRVoyZEZRa0ZHZFRKWFJqTndRalUyWVhkaFJGQXpWa3BXYW1ab01YbHVW
bTBLUkdkTGEwaEhlV05QYkZveVZVbElWbmx1VFRkc2JVWjZPR3Q1YVVGRVpFOW9aR2xDU1ZWbVdE
ZGlkMUZ3V0hCb1owd3JSbE5ETUhCS1prUjBWRUZIV1FwTlNsTjRXWEJMYmxOSlMzQndiVGRKYkVo
clNsUkJRME5aU0RSaVZTdERSbXBxU1U1eE0yUnVPVFp2YmxSdlVWRXlLemxhYTNCeFZ6aGpRV3Aw
VUZnekNtOHlMM0pLUlZKSFZHVkxUWE5IYlZSVFdqbHNkbmhOUW1wbVZtZGpNVmQxVVhnNFQyaGFP
V0puY2swM1dDOHJOWGhRUWxKclJEVTBkMEpJVUhZNGFrNEtXa1VyZVZCVGVqTk5hMUJNZG5GYWJr
SmFaV1oxYVRkNmR6VTJjR1ZaV2xSc1YxTXpUMVZUZVd4c1JHcFlkVWxZVUdwdWMxTklXR1Z3TDB4
MVVXVk9SZ3B5VldaMk5VZDNjRWhRWVdoNFJFRk1TMlV3ZDBkM01FSllTMUJsYTIxWFFtVTRVek5J
YUhWYWMySnRPRU0zYXpWU2FVZFdNVllyYjJ4Tk1EMEtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJW
RVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly9nYXRld2F5LnYwMjAzLmNjZTAxLnByZXNh
bGVzLmhwZWNvcnAubmV0OjEwMDAwCiAgbmFtZTogazhzLTEKY29udGV4dHM6Ci0gY29udGV4dDoK
ICAgIGNsdXN0ZXI6IGs4cy0xCiAgICB1c2VyOiBrdWJlcm5ldGVzLWFkbWluCiAgbmFtZToga3Vi
ZXJuZXRlcy1hZG1pbkBrOHMtMQpjdXJyZW50LWNvbnRleHQ6IGt1YmVybmV0ZXMtYWRtaW5Aazhz
LTEKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBrdWJlcm5ldGVz
LWFkbWluCiAgdXNlcjoKICAgIGNsaWVudC1jZXJ0aWZpY2F0ZS1kYXRhOiBMUzB0TFMxQ1JVZEpU
aUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNNGFrTkRRV1J4WjBGM1NVSkJaMGxKVEVacU1t
WTFhSEpUVWxWM1JGRlpTa3R2V2tsb2RtTk9RVkZGVEVKUlFYZEdWRVZVVFVKRlIwRXhWVVVLUVho
TlMyRXpWbWxhV0VwMVdsaFNiR042UVdWR2R6QjVUVVJCZVUxcVozaFBWRWw1VFZSc1lVWjNNSGxO
VkVGNVRXcGplRTlVU1hsTmFrNWhUVVJSZUFwR2VrRldRbWRPVmtKQmIxUkViazQxWXpOU2JHSlVj
SFJaV0U0d1dsaEtlazFTYTNkR2QxbEVWbEZSUkVWNFFuSmtWMHBzWTIwMWJHUkhWbnBNVjBackNt
SlhiSFZOU1VsQ1NXcEJUa0puYTNGb2EybEhPWGN3UWtGUlJVWkJRVTlEUVZFNFFVMUpTVUpEWjB0
RFFWRkZRVEZuUzJsMFFtbEhRVXhZYVUxSlpHTUtibFExUjBWb2JVaExTVGxwZUZacEsxb3ZOR1J5
UkdsT1JtcGFVU3RQVHpORWQzTk1NbUppTWsxalJGRnFOMHR5VFZKSldFZERPWE5OUmtjeGJIQXhS
QXB1ZG1WYWNHUm5SMVIxUjI5U1NXc3ZUbEZMUVZRM1VpdE5ZWHBhZEhsWUwwWTRXV1Z0YzFCNFJs
Qk9hRWxMY1RjdlEwMUxWREV6ZDFOaU9GcHFUVkZFQ2xoSE1WZE5WMkZ5Wm5sTlFuWnlSbEZ2Y0V4
U2NuTmlUWGQxUlU1WE9VcG9UM1pKZFd4V2FFWmplREI1U0ZGVFZYZzBjMFpvYkU1SVJESkNiM1pY
TUhVS2JDODNZazF0YTJ4aU55OXBWSEphVVcxd2VuaFNla293ZVZCRE9UZGhiVXh5TTAxWlpsTXpN
MUpZTUZwcmRWTmxVR1ZZWldwV1VITmhNbFkyY2twQ1dBcGtTVGxZZFU5aGVXbDZablpyUVRSWUwy
Uk1jbWxqT0U0M05uZ3JlRGhGWVVaeU5YSjFTMU56VVZaUFZVa3hTelJOUWpsQlIwcDBkQzg0YkdK
aE1XODBDazl2VVhScWQwbEVRVkZCUW05NVkzZEtWRUZQUW1kT1ZraFJPRUpCWmpoRlFrRk5RMEpo
UVhkRmQxbEVWbEl3YkVKQmQzZERaMWxKUzNkWlFrSlJWVWdLUVhkSmQwUlJXVXBMYjFwSmFIWmpU
a0ZSUlV4Q1VVRkVaMmRGUWtGSFozZDVVV2hNVXpWWlpTOUdMM2QzVTNoTVFURXdVMjR5VEZGeVRF
MU1ValV4WlFwSmF6QTJXVTUzYzJ4bWVHVTBaMEZuZVU1V1JXVjBlakJhYkZsa1RrVlpjelJ0SzNo
RWJucFRVVVJSTW1relJGTlNTMUZYY0M5MVVsVjRiMlpJVVdRMUNubHdielIxYkU1bmJUbGtibkph
VFU5VFJYSjZiVlpoTUdaUFJFaE5iV1ZwU1VzMGNHaFVWWE5HY2sxblN6WmpSVWxDU1V0RlZGZEdZ
bTVWVVhWVFFuUUtaRVptVjFKNlpEbHJSamhyTVV0UlFWWkVWVU5OYm5jemJVTlBWRnAzTlRoeFYw
VnJORkJ1TWs1NWRqRXdUblJCTWk5S2ExUm1aMGhrVUcwMmNVaFROUXBEVEhGSGFpOVRNMGR5ZEZj
NVFuQkhVMDVuY25waE5HOUJZbXQ1WmxGaFFsbFBVVTE1Um0xYVFsQm1OR3RpWlRrMlNGVm1kbE5K
ZFVGU00xcFVlVk5zQ2tkbk1sTTJjSFptY1NzMVQwWTNha3hhWTBKMVNHSlRXR0ZWVVcxSVNsbDVi
a05qVlhwU2MxRmFTREpVYjNaa1dtWjZNRDBLTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExT
MHRMUW89CiAgICBjbGllbnQta2V5LWRhdGE6IExTMHRMUzFDUlVkSlRpQlNVMEVnVUZKSlZrRlVS
U0JMUlZrdExTMHRMUXBOU1VsRmIzZEpRa0ZCUzBOQlVVVkJNV2RMYVhSQ2FVZEJURmhwVFVsa1ky
NVVOVWRGYUcxSVMwazVhWGhXYVN0YUx6Umtja1JwVGtacVdsRXJUMDh6Q2tSM2Mwd3lZbUl5VFdO
RVVXbzNTM0pOVWtsWVIwTTVjMDFHUnpGc2NERkViblpsV25Ca1owZFVkVWR2VWtsckwwNVJTMEZV
TjFJclRXRjZXblI1V0M4S1JqaFpaVzF6VUhoR1VFNW9TVXR4Tnk5RFRVdFVNVE4zVTJJNFdtcE5V
VVJZUnpGWFRWZGhjbVo1VFVKMmNrWlJiM0JNVW5KellrMTNkVVZPVnpsS2FBcFBka2wxYkZab1Jt
TjRNSGxJVVZOVmVEUnpSbWhzVGtoRU1rSnZkbGN3ZFd3dk4ySk5iV3RzWWpjdmFWUnlXbEZ0Y0hw
NFVucEtNSGxRUXprM1lXMU1Dbkl6VFZsbVV6TXpVbGd3V210MVUyVlFaVmhsYWxaUWMyRXlWalp5
U2tKWVpFazVXSFZQWVhscGVtWjJhMEUwV0M5a1RISnBZemhPTnpaNEszZzRSV0VLUm5JMWNuVkxV
M05SVms5VlNURkxORTFDT1VGSFNuUjBMemhzWW1FeGJ6UlBiMUYwYW5kSlJFRlJRVUpCYjBsQ1FV
ZHlPV3BzU0hwSlMzTnBVWGcxTXdwNllteGxPVXhFTDNscE5XYzBUVkpCYUZwQ0x6TnNNMGhPSzBk
MU4yWlNRVUUzYVd4clVuTmhLMU5KVDJaNldWZzBURmczYTFWbmNVUlVRbkUyVW0xUUNreGpjeTlv
WWxRdmRITmxaekJRY2xOcmNVeDRlVk4zVURGRVkwcGllRFk1UWtSaWFXVldTblZQZDNnMlZVVnBR
V3QwUzA5M1ozcEVjbVZzZDJaR2JDOEtaRkkyTUVkeE9DODBUMVZEYmpGRGVWaE9iWEZDVDBsWWVW
TTFlbGxxYUhObk5sSk9WRk5QVjB3NGMzUlRiU3MxU1hWeldIUXhOR1o2TTFSNU5HVk5UQXBMUm5W
VVlXSkhValZMYTBOMGMySk5UbmhuT1haRGR6WkhaRTgyTDBwNldXbEZVWFZOVTNBMGFHb3dUelZV
VVdZemJGcFlkWGRrTVZWR1lYRTVZMm93Q25CdFZHMXBiaXN6WmtaMWMzUkhSSEptWjAxQldrbHJT
azVXVld0eFpuWTBRbUpqWVc1MFVqRXpVVVF2WlU5U1UwNHJhSFpUZG5OeFRHeEdRMGx4Tms0S2VI
WkJWa3BEUlVObldVVkJNaXQwY0V4cEwxRkpVbVJJUlhjdmJYbFljbmRtUjJ0bmExRm9NM2w1VFVo
YVdIbGtlaTlrVHpkWFNYaDJjRzFUUkcxYWNBcDFiVTVzWTAweVRVcDVNazFRT0RWaUsydDRlakpX
Yms5Q2IxTlFXQzl4U0RsRlJuZ3pUV1JUVFVsR2FtOVdNRzQyVkd0WGNIZExPRVZJYTJ4VFIwbHVD
a2t6UW5KSVEwYzRhRWRaWVZwdlNrWmpWMjR2YUdaMU1rdE1kbUZyVGtSdk9HWlJlVkZ5TkZKdWJr
dDNaMHQ0Y0Rsd1J6QkJjM05EWjFsRlFTdFNPRW9LVEN0c2JraE5WRVYzVkhwNlF6QXdhVk0wWlU5
bFRFcFBlRVl3V0RJMGRUTnVlRlU0UWpaalR6aFNlWGhUU0VSeE16SkRXRWx4VEV4RGNWZHFUREpW
ZEFwa2FXazBaMnAzYkZaWlJIQmtVRUYwVVRWVVZXOW5lV3BSVmpReU5HY3ZXbXQ0UjBabmJFRjZa
V3BMUW1sdmJrTkdXV3g1TkVzelFrOXJTbW8wU2tvMkNrUlZSMmswVURabVRHZ3dWWHBIYTJOUk1Y
RklhVEZ2VUdWTlQwSndhVkJ4Wm00M0szTTRNRU5uV1VGTWVuWXdjakZNWkhCUU0xYzJhVlV3VFVo
dlZGSUtUMVptWkZWaldWVTJNRWRZWVc1VFV6SlRWM041TW5ZcldIZExabk5XU1ZkQ2QxcEpXVEZG
VjFCWVZHUmlSR2N5U0ZkeVVFUmxjSEJKVXpoT2NWVmpjQXBxTWxsTmR6aHpaUzloVDJFME5GTnJS
MnRQYTBob2NEVkRMMmMzYUdOSGVWQnVVVkkwTmtoaGRtaDZSM2xzU0hWUlFraFFXVThyYzBOclNU
Tkxia05JQ25CWFVWcG1NV3N3TVRsWGQxbDRSMmhuY25SWGRIZExRbWRSUkVzM1lqUnNSMmxMVm1F
Mkt5dHVWRUkyUkhvMFZtVnVibE14WVZOWFJHbE5iVUYwZW5vS2NVYzVOalpHYldscVRGaGFRbUZ2
T1doalpqTlFaR0phWlVjelEyRk5LM05vWVZWMU5sZEhZMFZsVDJGRWVEbEJRWFJrYlc1YVlrczBO
ekJtVkhKMk1BcE5abmx2Vm5vMWJteDNZWGN6UjBOT0wwdFliMWxaUjJGUVNWSjRXbU5CYjFaclVX
ZDBVMnBxWm0xeU0zazVUbkpDYVRaT2JFUkpkMDVGYmtSR1ZsTndDamhFWWpSTVVVdENaMGhoVDFV
d2VXbHBTMlF5Y2xoUE4wOXJWM2cyWkV4aE5DdEhNREp4Vm5Sck5VVTBielJ2VkhWa09WQkdiMmR2
UmxkSlNsSXlURUVLYm0xRk1HMXNjVlZHU1d4aFUyRTRkRE00V1d4SFVreGtVR1F4UjB4RFJHMUZk
MDF0VUZoRFJtWkthMlF3Y0VsQlJ6QnNPRmxOYWtSS1EwWmxRblF2U2dwVFZHOVVlVmRuS3poUVlY
UkllbXhuV2xVd1YwWktaRkpCVWxFMlRISmlTVkZYUkhwR01qTnRibGh0UjJKTVlqSnJkR1Z6Q2kw
dExTMHRSVTVFSUZKVFFTQlFVa2xXUVZSRklFdEZXUzB0TFMwdENnPT0='
orbs:
  kube-orb: circleci/kubernetes@0.11.0
version: 2.1