jobs:
  build:
    macos:
      xcode: '9.0'
    steps:
      - checkout
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
orbs:
  kube-orb: circleci/kubernetes@0.11.0
version: 2.1