version: 2.1

orbs:
  node: circleci/node@1.1.6
  kube-orb: circleci/kubernetes@0.11.0
jobs:
  build:
    machine: true
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  #build-kubeconfig:
  #  machine: true
  #  steps:
  #    - checkout
  #    - kube-orb/install-kubeconfig:
  #        kubeconfig: KUBECONFIG_DATA
  #build-kubectl:
  #  machine: true
  #  steps:
  #    - checkout
  #    - kube-orb/install-kubectl

  deploy:
    machine: true
    steps:
      - checkout
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kube-orb/install-kubectl
      - run:
          name: Deploy using kustomize
          command: |
            kubectl apply -k deploy-kustomize

workflows:
  build_update_deploy:
    jobs:
      - build
      #- install-kubeconfig:
      #    requires:
      #      - build
      #- install-kubectl:
      #    requires:
      #      - install-kubeconfig
      - deploy:
          requires:
            - build
      
