version: 2.1

orbs:
  node: circleci/node@1.1.6
  Kubernetes: circleci/kubernetes@0.11.0
  kube-orb: circleci/kubernetes@1.0.0
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install

  install-kubectl-kubeconfig:
    description: install-kubectl-kubeconfig
    machine: true
    steps:
      - checkout
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
    steps:
      - checkout
      - kube-orb/install-kubectl

  deploy:
    description: Deploy application to HPE HCP Kubernetes Engine
    machine: true
    docker:
      - image: 'prakashmirji/circleci-simple-app:v2'
    steps:
      - checkout
      - kube-orb/install-kubectl
      - run:
          name: Deploy using kustomize
          command: |
            kubectl apply -k deploy-kustomize

workflows:
  build_update_deploy:
    jobs:
      - build
      - install-kubectl-kubeconfig:
          requires:
            - build
      - deploy:
          requires:
            - install-kubectl-kubeconfig
      
